Repository Abhishek2634/Foodie, pull requests merged in 2025-08, with the labels that each got.

#237 [DOCS]: add LEARN.md and link it in README and CONTRIBUTING
  CONTRIBUTING.md
  LEARN.md
  README.md
Labels: GSSOC25, level-2

#232 Enhance: Redesigned mobile header and navbar for better UI/UX
  frontend/src/components/Chatbot/Chatbot.css
  frontend/src/components/Header/Header.css
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/components/SearchBar/SearchBar.css
Labels: GSSOC25, level-2

#258 [DOCS]: improve README navigation and quick links
  README.md
Labels: GSSOC25, level-3

#275 Add Contact Form
  .gitignore
  frontend/src/App.jsx
  frontend/src/components/ContactForm/ContactForm.css
  frontend/src/components/ContactForm/ContactForm.jsx
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/pages/Contactpage.jsx
  package-lock.json
Labels: GSSOC25, level-2

#285 ENHANCING CONTACT PAGE
  frontend/src/components/ContactForm/ContactForm.css
  frontend/src/components/ContactForm/ContactForm.jsx
Labels: GSSOC25, level-2

#287 ENHANCE : the footer context is in computer language eg. lorem
  frontend/src/components/Footer/Footer.css
  frontend/src/components/Footer/Footer.jsx
Labels: GSSOC25, Level-1

#264 ✨ Add clickable restaurant cards and expandable review section #263
  frontend/src/App.jsx
  frontend/src/pages/Restaurants/RestaurantDetail.jsx
  frontend/src/pages/Restaurants/Restaurants.jsx
Labels: GSSOC25, level-2

#236 Updated Navbar component
  admin/src/components/Navbar/Navbar.css
  admin/src/components/Navbar/Navbar.jsx
Labels: GSSOC25, Level-1

#316 feat: Logout function added
  backend/controllers/authController.js
Labels: GSSOC25, Level-1

#334 fix: font color for dark mode login sign up
  frontend/src/index.css
Labels: GSSOC25, Level-1

#346 "Enhance Restaurant Detail Page: Added Styled Back Button"
  .vite/deps/vercel.json
  frontend/src/pages/Restaurants/RestaurantDetail.jsx
  frontend/src/pages/Restaurants/Restaurants.css
Labels: GSSOC25, Level-1

#375 Added about us page and updated footer [GSSOC'25 Contribution]
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/assets/frontend_assets/foodie_illustration.png
  frontend/src/components/Footer/Footer.css
  frontend/src/components/Footer/Footer.jsx
  frontend/src/pages/AboutPage/AboutPage.css
  frontend/src/pages/AboutPage/AboutPage.jsx
Labels: GSSOC25, level-3

#387 Link git adding
  frontend/public/github(20).png
  frontend/src/components/Footer/Footer.jsx
Labels: GSSOC25, Level-1

#394 Navigation-Enhancement.
  frontend/src/App.jsx
  frontend/src/components/ScrollToBottomButton/ScrollToBottomButton.css
  frontend/src/components/ScrollToBottomButton/ScrollToBottomButton.jsx
Labels: GSSOC25, level-2

#392 Enhanced Wishlist Functionality and Navbar Improvements
  frontend/src/App.jsx
  frontend/src/components/FoodItem/FoodItem.css
  frontend/src/components/FoodItem/FoodItem.jsx
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/components/context/StoreContext.jsx
  frontend/src/pages/wishlist/wishlist.jsx
Labels: GSSOC25, level-3

#406 feat(auth): Add password strength checker to signup form
  frontend/src/components/LoginPopup/LoginPopup.css
  frontend/src/components/LoginPopup/LoginPopup.jsx
Labels: GSSOC25, level-2

#414 correct distortion in dark mode & scroll-to-top buttons
  frontend/src/components/Navbar/Navbar.css
  frontend/src/components/Navbar/Navbar.jsx
  frontend/src/components/ScrollToBottomButton/ScrollToBottomButton.css
  frontend/src/components/ScrollToTopButton/ScrollToTopButton.css
Labels: GSSOC25, level-2

#418 Feat/auto pr comment
  .github/workflows/auto-comment.yml
Labels: GSSOC25, level-2

#396 Add Print & Export PDF feature for FoodDetail page
  CONTRIBUTING.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/FoodDetail/FoodDetail.jsx
  frontend/src/components/FoodDetail/print.css
  package-lock.json
  package.json
Labels: GSSOC25, level-3

#423 Add cuisine-specific restaurant search with search bar
  admin/package-lock.json
  frontend/src/components/AppDownlad/AppDownload.css
  frontend/src/index.css
  frontend/src/pages/Restaurants/Restaurants.jsx
Labels: GSSOC25, level-2

#489 Replace PNG icons with SVG components in Footer
  frontend/src/components/Footer/Footer.jsx
  frontend/src/components/Icons/FacebookIcon.jsx
  frontend/src/components/Icons/GithubIcon.jsx
  frontend/src/components/Icons/LinkedInIcon.jsx
  frontend/src/components/Icons/TwitterIcon.jsx
Labels: GSSOC25, level-2

#503 fix the footer issue
  frontend/src/components/Footer/Footer.jsx
Labels: GSSOC25, level-2

#498 Foodie logo in dark mode
  frontend/src/components/Navbar/Navbar.css
Labels: GSSOC25, Level-1

#504 Added the confirm password field.
  frontend/src/components/LoginPopup/LoginPopup.jsx
Labels: GSSOC25, level-2
