Repository Abhishek2634/Foodie, pull requests merged in 2025-09, with the labels that each got.

#529 Fix Login/Signup Page Styling Issues
  frontend/package-lock.json
  frontend/src/components/LoginPopup/LoginPopup.css
Labels: GSSOC25, level-2

#544 Fixed cart quantity limit issue
  frontend/src/components/FoodDetail/FoodDetail.jsx
  frontend/src/components/FoodItem/FoodItem.css
  frontend/src/components/FoodItem/FoodItem.jsx
  frontend/src/components/context/StoreContext.jsx
  frontend/src/pages/Cart/Cart.css
  frontend/src/pages/Cart/Cart.jsx
Labels: GSSOC25, level-2

#560 Fix: AI chatbot using Gimini API key
  frontend/src/components/Chatbot/Chatbot.jsx
Labels: GSSOC25, level-2

#559 Added share option (whatsapp, X, Mail, facebook) for food items
  frontend/src/components/FoodDetail/FoodDetail.jsx
Labels: GSSOC25, level-2

#601 Center Align Filter Buttons (All, Veg, Non-Veg) Under Top Dishes Near You SectionUpdate FoodDisplay.css
  frontend/src/components/FoodDisplay/FoodDisplay.css
Labels: GSSOC25, Level-1

#611 [GSSoc 2025] Fixed Rendering Issue, updated Footer Component in Frontend and App routes, tested locally
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/main.jsx
  frontend/vite.config.js
Labels: GSSOC25, level-2

#610 Adding space(margin) between Back to restaurants and image
  frontend/src/components/FoodDetail/FoodDetail.css
  frontend/src/pages/Restaurants/RestaurantDetail.jsx
Labels: GSSOC25, Level-1

#613 fix: update footer logo and hover effect, change footer background
  frontend/src/components/Footer/Footer.css
  frontend/src/components/Footer/Footer.jsx
  frontend/src/components/Footer/FooterLogo.jsx
Labels: GSSOC25, level-2

#614 Hover animation changes on menu list made
  admin/package-lock.json
  admin/package.json
  frontend/src/components/ExploreMenu/ExploreMenu.css
Labels: GSSOC25, level-2

#617 Correct alignment of checkbox in Order together section
  frontend/src/components/FoodDetail/OrderTogether.css
  frontend/src/components/FoodDetail/OrderTogether.jsx
Labels: GSSOC25, level-2

#621 UI Issues Fix (Issue #609)
  frontend/src/components/Aboutus/AboutUs.css
  frontend/src/components/Aboutus/Aboutus.jsx
Labels: GSSOC25, level-2

#646 Added "Show/Hide Password" Eye Icon in Signup and Login Forms
  frontend/src/components/LoginPopup/LoginPopup.css
  frontend/src/components/LoginPopup/LoginPopup.jsx
Labels: GSSOC25, level-2

#672 Fix dark mode visibility issues in review cards
  frontend/src/components/FoodDetail/FoodDetail.css
Labels: GSSOC25, Level-1

#644 Fixing sign in and login issue
  AUTHENTICATION_SETUP.md
  backend/controllers/authController.js
  backend/routes/authRoute.js
  frontend/src/App.jsx
  frontend/src/components/Aboutus/AboutUs.css
  frontend/src/components/Aboutus/Aboutus.jsx
  frontend/src/components/LoginPopup/LoginPopup.jsx
  frontend/src/components/Navbar/Navbar.jsx
Labels: GSSOC25, level-3
